### ISSUE TITLE
Any way to trigger the image picker from a Nova field

### ISSUE THREAD

**Issue by graphem** [mostafaznv/nova-larupload#14]
Hi, I am using the CK5Editor for nova, and it comes with the Image Picker that comes up where you can select an Image or upload it.

I am wondering if there is a way to use the image picker with the nova-file-artisan package to trigger the image picker when adding media via a Nova field.

Thanks!

**Comment by mostafaznv** [comment]
Hi @graphem,
For now, `NovaCkEditor` is not compatible with `NovaFileArtisan` but I think it's a good idea. I will give a try on it untill up to the weekend and will inform you the result.

Related to: https://github.com/mostafaznv/nova-ckeditor/issues/94

**Comment by mostafaznv** [comment]
Hi again.
Your requested feature has been published under [6.1.0](https://github.com/mostafaznv/nova-ckeditor/releases/tag/6.1.0).
Please update `NovaCkEditor` to the latest version and follow the instruction bellow:

https://mostafaznv.gitbook.io/nova-ckeditor/advanced-usage/integrating-novafileartisan-larupload-with-image-resource
